export const path = {
  login: "login",
  register: "register",
  forgotPass: "forgot-password",

  product: "product/:id",
  adminAddProduct: "admin-bookgrid/add-product",
  adminProduct: "admin-bookgrid/product/:id",
  adminBookReviews: "admin/book-reviews",
  adminCustomers: "admin/customers",
  cart: "cart",
  search: "search",
  payment_success: "/payment-success",
  checkout: "/order-checkout",
  orderSummary: "order-summary",
  notificationPage: "notification-page",
  customerOrder: "my-orders",
  customerCoupon: "my-coupons",
  customerAccount: "my-account",
  customerOrderTracking: "order",

  adminDashboard: "admin-dashboard",
  adminProducts: "admin-bookgrid",
  adminBookDetail: "admin-bookdetail",
  adminAccount: "admin-account",
  adminAddVoucher: "admin-add-voucher",
  adminOrderManagement: "admin-order",
  adminVoucherManagement: "admin-voucher-management",
  adminCustomerAccount: "admin-customer-account/:userId"
};
